---
- name: Restart tftpd-hpa
  ansible.builtin.service:
    name: tftpd-hpa
    state: restarted
  become: true

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  become: true
