---
iscsi_state: present
iscsi_portal: ""
iscsi_target_iqn: ""
iscsi_chap_user: ""
iscsi_chap_password: ""
iscsi_mode: "host_mount"
iscsi_mount_path: "/mnt/data"
iscsi_filesystem: "ext4"
iscsi_port: 3260
iscsi_nfs_export: ""
iscsi_op_item: ""
iscsi_op_token_file: /etc/olympus/op-service-account-token
