---
- name: iSCSI — macOS
  ansible.builtin.include_tasks: macos.yml
  when:
    - ansible_facts['os_family'] == "Darwin"
    - iscsi_state == "present"

- name: iSCSI — Linux host_mount
  ansible.builtin.include_tasks: linux_host_mount.yml
  when:
    - ansible_facts['os_family'] == "Debian"
    - iscsi_mode == "host_mount"
    - iscsi_state == "present"

- name: iSCSI — Linux initiator_only
  ansible.builtin.include_tasks: linux_initiator_only.yml
  when:
    - ansible_facts['os_family'] == "Debian"
    - iscsi_mode == "initiator_only"
    - iscsi_state == "present"

- name: iSCSI — Linux csi_node
  ansible.builtin.include_tasks: linux_csi_node.yml
  when:
    - ansible_facts['os_family'] == "Debian"
    - iscsi_mode == "csi_node"
    - iscsi_state == "present"
