---
- name: Restart iscsid
  ansible.builtin.systemd:
    name: iscsid
    state: restarted
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Restart multipathd
  ansible.builtin.systemd:
    name: multipathd
    state: restarted
  become: true
  when: ansible_facts['os_family'] == "Debian"
