---
- name: restart sshd
  ansible.builtin.service:
    name: "{{ 'ssh' if ansible_facts['os_family'] == 'Debian' else 'sshd' }}"
    state: restarted
  become: true

- name: restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  become: true

- name: restart timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted
  become: true
